---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "uname" . }}-pdb"
{{- if .Values.annotations }}
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "uname" . }}"
{{- end }}
